In [48]:
#Import the required libraries
import numpy as np
import pandas as pd

# Train Dataset

In [49]:
db_train =pd.read_csv('train.csv')

In [50]:
db_train

ID       y  X0 X1  X2 X3 X4  X5 X6 X8  ...  X375  X376  X377  X378  \
0        0  130.81   k  v  at  a  d   u  j  o  ...     0     0     1     0   
1        6   88.53   k  t  av  e  d   y  l  o  ...     1     0     0     0   
2        7   76.26  az  w   n  c  d   x  j  x  ...     0     0     0     0   
3        9   80.62  az  t   n  f  d   x  l  e  ...     0     0     0     0   
4       13   78.02  az  v   n  f  d   h  d  n  ...     0     0     0     0   
...    ...     ...  .. ..  .. .. ..  .. .. ..  ...   ...   ...   ...   ...   
4204  8405  107.39  ak  s  as  c  d  aa  d  q  ...     1     0     0     0   
4205  8406  108.77   j  o   t  d  d  aa  h  h  ...     0     1     0     0   
4206  8412  109.22  ak  v   r  a  d  aa  g  e  ...     0     0     1     0   
4207  8415   87.48  al  r   e  f  d  aa  l  u  ...     0     0     0     0   
4208  8417  110.85   z  r  ae  c  d  aa  g  w  ...     1     0     0     0   

      X379  X380  X382  X383  X384  X385  
0        0     0     0     0     0     0  
1        0     0     0     0     0     0  
2        0     0     1     0     0     0  
3        0     0     0     0     0     0  
4        0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...  
4204     0     0     0     0     0     0  
4205     0     0     0     0     0     0  
4206     0     0     0     0     0     0  
4207     0     0     0     0     0     0  
4208     0     0     0     0     0     0  

[4209 rows x 378 columns]

In [51]:
db_train.shape

(4209, 378)

# Test Dataset

In [52]:
db_test =pd.read_csv('test.csv')

In [53]:
db_test

ID  X0  X1  X2 X3 X4  X5 X6 X8  X10  ...  X375  X376  X377  X378  \
0        1  az   v   n  f  d   t  a  w    0  ...     0     0     0     1   
1        2   t   b  ai  a  d   b  g  y    0  ...     0     0     1     0   
2        3  az   v  as  f  d   a  j  j    0  ...     0     0     0     1   
3        4  az   l   n  f  d   z  l  n    0  ...     0     0     0     1   
4        5   w   s  as  c  d   y  i  m    0  ...     1     0     0     0   
...    ...  ..  ..  .. .. ..  .. .. ..  ...  ...   ...   ...   ...   ...   
4204  8410  aj   h  as  f  d  aa  j  e    0  ...     0     0     0     0   
4205  8411   t  aa  ai  d  d  aa  j  y    0  ...     0     1     0     0   
4206  8413   y   v  as  f  d  aa  d  w    0  ...     0     0     0     0   
4207  8414  ak   v  as  a  d  aa  c  q    0  ...     0     0     1     0   
4208  8416   t  aa  ai  c  d  aa  g  r    0  ...     1     0     0     0   

      X379  X380  X382  X383  X384  X385  
0        0     0     0     0     0     0  
1        0     0     0     0     0     0  
2        0     0     0     0     0     0  
3        0     0     0     0     0     0  
4        0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...  
4204     0     0     0     0     0     0  
4205     0     0     0     0     0     0  
4206     0     0     0     0     0     0  
4207     0     0     0     0     0     0  
4208     0     0     0     0     0     0  

[4209 rows x 377 columns]

In [54]:
db_test.shape

(4209, 377)

# If for any column(s), the variance is equal to zero, then you need to remove those variable(s)

In [55]:
db_test.var()[db_test.var()==0]

X257    0.0
X258    0.0
X295    0.0
X296    0.0
X369    0.0
dtype: float64

In [56]:
db_test=db_test.drop(db_test[['X257','X258','X295','X296','X369']],axis=1)

In [57]:
db_test

ID  X0  X1  X2 X3 X4  X5 X6 X8  X10  ...  X375  X376  X377  X378  \
0        1  az   v   n  f  d   t  a  w    0  ...     0     0     0     1   
1        2   t   b  ai  a  d   b  g  y    0  ...     0     0     1     0   
2        3  az   v  as  f  d   a  j  j    0  ...     0     0     0     1   
3        4  az   l   n  f  d   z  l  n    0  ...     0     0     0     1   
4        5   w   s  as  c  d   y  i  m    0  ...     1     0     0     0   
...    ...  ..  ..  .. .. ..  .. .. ..  ...  ...   ...   ...   ...   ...   
4204  8410  aj   h  as  f  d  aa  j  e    0  ...     0     0     0     0   
4205  8411   t  aa  ai  d  d  aa  j  y    0  ...     0     1     0     0   
4206  8413   y   v  as  f  d  aa  d  w    0  ...     0     0     0     0   
4207  8414  ak   v  as  a  d  aa  c  q    0  ...     0     0     1     0   
4208  8416   t  aa  ai  c  d  aa  g  r    0  ...     1     0     0     0   

      X379  X380  X382  X383  X384  X385  
0        0     0     0     0     0     0  
1        0     0     0     0     0     0  
2        0     0     0     0     0     0  
3        0     0     0     0     0     0  
4        0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...  
4204     0     0     0     0     0     0  
4205     0     0     0     0     0     0  
4206     0     0     0     0     0     0  
4207     0     0     0     0     0     0  
4208     0     0     0     0     0     0  

[4209 rows x 372 columns]

In [58]:
db_train.var()[db_train.var()==0]

X11     0.0
X93     0.0
X107    0.0
X233    0.0
X235    0.0
X268    0.0
X289    0.0
X290    0.0
X293    0.0
X297    0.0
X330    0.0
X347    0.0
dtype: float64

In [59]:
db_train=db_train.drop(db_train[['X11','X93','X107','X233','X235','X268','X289','X290','X293','X297','X330','X347']],axis=1)

In [60]:
db_train

ID       y  X0 X1  X2 X3 X4  X5 X6 X8  ...  X375  X376  X377  X378  \
0        0  130.81   k  v  at  a  d   u  j  o  ...     0     0     1     0   
1        6   88.53   k  t  av  e  d   y  l  o  ...     1     0     0     0   
2        7   76.26  az  w   n  c  d   x  j  x  ...     0     0     0     0   
3        9   80.62  az  t   n  f  d   x  l  e  ...     0     0     0     0   
4       13   78.02  az  v   n  f  d   h  d  n  ...     0     0     0     0   
...    ...     ...  .. ..  .. .. ..  .. .. ..  ...   ...   ...   ...   ...   
4204  8405  107.39  ak  s  as  c  d  aa  d  q  ...     1     0     0     0   
4205  8406  108.77   j  o   t  d  d  aa  h  h  ...     0     1     0     0   
4206  8412  109.22  ak  v   r  a  d  aa  g  e  ...     0     0     1     0   
4207  8415   87.48  al  r   e  f  d  aa  l  u  ...     0     0     0     0   
4208  8417  110.85   z  r  ae  c  d  aa  g  w  ...     1     0     0     0   

      X379  X380  X382  X383  X384  X385  
0        0     0     0     0     0     0  
1        0     0     0     0     0     0  
2        0     0     1     0     0     0  
3        0     0     0     0     0     0  
4        0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...  
4204     0     0     0     0     0     0  
4205     0     0     0     0     0     0  
4206     0     0     0     0     0     0  
4207     0     0     0     0     0     0  
4208     0     0     0     0     0     0  

[4209 rows x 366 columns]

# Check for null and unique values for test and train sets.

In [61]:
db_test.isna().sum().any()

False

In [62]:
db_test.nunique()

ID      4209
X0        49
X1        27
X2        45
X3         7
        ... 
X380       2
X382       2
X383       2
X384       2
X385       2
Length: 372, dtype: int64

In [63]:
db_train.isna().sum().any()

False

In [64]:
db_train.nunique()

ID      4209
y       2545
X0        47
X1        27
X2        44
        ... 
X380       2
X382       2
X383       2
X384       2
X385       2
Length: 366, dtype: int64

# Apply label encoder.

In [65]:
from sklearn.preprocessing import LabelEncoder

In [66]:
le=LabelEncoder()

In [67]:
db_test=db_test.drop(['ID'],axis=1)

In [68]:
db_test

X0  X1  X2 X3 X4  X5 X6 X8  X10  X11  ...  X375  X376  X377  X378  X379  \
0     az   v   n  f  d   t  a  w    0    0  ...     0     0     0     1     0   
1      t   b  ai  a  d   b  g  y    0    0  ...     0     0     1     0     0   
2     az   v  as  f  d   a  j  j    0    0  ...     0     0     0     1     0   
3     az   l   n  f  d   z  l  n    0    0  ...     0     0     0     1     0   
4      w   s  as  c  d   y  i  m    0    0  ...     1     0     0     0     0   
...   ..  ..  .. .. ..  .. .. ..  ...  ...  ...   ...   ...   ...   ...   ...   
4204  aj   h  as  f  d  aa  j  e    0    0  ...     0     0     0     0     0   
4205   t  aa  ai  d  d  aa  j  y    0    0  ...     0     1     0     0     0   
4206   y   v  as  f  d  aa  d  w    0    0  ...     0     0     0     0     0   
4207  ak   v  as  a  d  aa  c  q    0    0  ...     0     0     1     0     0   
4208   t  aa  ai  c  d  aa  g  r    0    0  ...     1     0     0     0     0   

      X380  X382  X383  X384  X385  
0        0     0     0     0     0  
1        0     0     0     0     0  
2        0     0     0     0     0  
3        0     0     0     0     0  
4        0     0     0     0     0  
...    ...   ...   ...   ...   ...  
4204     0     0     0     0     0  
4205     0     0     0     0     0  
4206     0     0     0     0     0  
4207     0     0     0     0     0  
4208     0     0     0     0     0  

[4209 rows x 371 columns]

In [69]:
db_test=db_test.apply(le.fit_transform)

In [70]:
db_test

X0  X1  X2  X3  X4  X5  X6  X8  X10  X11  ...  X375  X376  X377  X378  \
0     21  23  34   5   3  26   0  22    0    0  ...     0     0     0     1   
1     42   3   8   0   3   9   6  24    0    0  ...     0     0     1     0   
2     21  23  17   5   3   0   9   9    0    0  ...     0     0     0     1   
3     21  13  34   5   3  31  11  13    0    0  ...     0     0     0     1   
4     45  20  17   2   3  30   8  12    0    0  ...     1     0     0     0   
...   ..  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...   ...   ...   ...   ...   
4204   6   9  17   5   3   1   9   4    0    0  ...     0     0     0     0   
4205  42   1   8   3   3   1   9  24    0    0  ...     0     1     0     0   
4206  47  23  17   5   3   1   3  22    0    0  ...     0     0     0     0   
4207   7  23  17   0   3   1   2  16    0    0  ...     0     0     1     0   
4208  42   1   8   2   3   1   6  17    0    0  ...     1     0     0     0   

      X379  X380  X382  X383  X384  X385  
0        0     0     0     0     0     0  
1        0     0     0     0     0     0  
2        0     0     0     0     0     0  
3        0     0     0     0     0     0  
4        0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...  
4204     0     0     0     0     0     0  
4205     0     0     0     0     0     0  
4206     0     0     0     0     0     0  
4207     0     0     0     0     0     0  
4208     0     0     0     0     0     0  

[4209 rows x 371 columns]

In [71]:
db_train

ID       y  X0 X1  X2 X3 X4  X5 X6 X8  ...  X375  X376  X377  X378  \
0        0  130.81   k  v  at  a  d   u  j  o  ...     0     0     1     0   
1        6   88.53   k  t  av  e  d   y  l  o  ...     1     0     0     0   
2        7   76.26  az  w   n  c  d   x  j  x  ...     0     0     0     0   
3        9   80.62  az  t   n  f  d   x  l  e  ...     0     0     0     0   
4       13   78.02  az  v   n  f  d   h  d  n  ...     0     0     0     0   
...    ...     ...  .. ..  .. .. ..  .. .. ..  ...   ...   ...   ...   ...   
4204  8405  107.39  ak  s  as  c  d  aa  d  q  ...     1     0     0     0   
4205  8406  108.77   j  o   t  d  d  aa  h  h  ...     0     1     0     0   
4206  8412  109.22  ak  v   r  a  d  aa  g  e  ...     0     0     1     0   
4207  8415   87.48  al  r   e  f  d  aa  l  u  ...     0     0     0     0   
4208  8417  110.85   z  r  ae  c  d  aa  g  w  ...     1     0     0     0   

      X379  X380  X382  X383  X384  X385  
0        0     0     0     0     0     0  
1        0     0     0     0     0     0  
2        0     0     1     0     0     0  
3        0     0     0     0     0     0  
4        0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...  
4204     0     0     0     0     0     0  
4205     0     0     0     0     0     0  
4206     0     0     0     0     0     0  
4207     0     0     0     0     0     0  
4208     0     0     0     0     0     0  

[4209 rows x 366 columns]

In [72]:
train=db_train.drop(db_train[['ID','y']],axis=1)

In [73]:
train

X0 X1  X2 X3 X4  X5 X6 X8  X10  X12  ...  X375  X376  X377  X378  X379  \
0      k  v  at  a  d   u  j  o    0    0  ...     0     0     1     0     0   
1      k  t  av  e  d   y  l  o    0    0  ...     1     0     0     0     0   
2     az  w   n  c  d   x  j  x    0    0  ...     0     0     0     0     0   
3     az  t   n  f  d   x  l  e    0    0  ...     0     0     0     0     0   
4     az  v   n  f  d   h  d  n    0    0  ...     0     0     0     0     0   
...   .. ..  .. .. ..  .. .. ..  ...  ...  ...   ...   ...   ...   ...   ...   
4204  ak  s  as  c  d  aa  d  q    0    0  ...     1     0     0     0     0   
4205   j  o   t  d  d  aa  h  h    0    0  ...     0     1     0     0     0   
4206  ak  v   r  a  d  aa  g  e    0    1  ...     0     0     1     0     0   
4207  al  r   e  f  d  aa  l  u    0    0  ...     0     0     0     0     0   
4208   z  r  ae  c  d  aa  g  w    0    0  ...     1     0     0     0     0   

      X380  X382  X383  X384  X385  
0        0     0     0     0     0  
1        0     0     0     0     0  
2        0     1     0     0     0  
3        0     0     0     0     0  
4        0     0     0     0     0  
...    ...   ...   ...   ...   ...  
4204     0     0     0     0     0  
4205     0     0     0     0     0  
4206     0     0     0     0     0  
4207     0     0     0     0     0  
4208     0     0     0     0     0  

[4209 rows x 364 columns]

In [74]:
train=train.apply(le.fit_transform)
train

X0  X1  X2  X3  X4  X5  X6  X8  X10  X12  ...  X375  X376  X377  X378  \
0     32  23  17   0   3  24   9  14    0    0  ...     0     0     1     0   
1     32  21  19   4   3  28  11  14    0    0  ...     1     0     0     0   
2     20  24  34   2   3  27   9  23    0    0  ...     0     0     0     0   
3     20  21  34   5   3  27  11   4    0    0  ...     0     0     0     0   
4     20  23  34   5   3  12   3  13    0    0  ...     0     0     0     0   
...   ..  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...   ...   ...   ...   ...   
4204   8  20  16   2   3   0   3  16    0    0  ...     1     0     0     0   
4205  31  16  40   3   3   0   7   7    0    0  ...     0     1     0     0   
4206   8  23  38   0   3   0   6   4    0    1  ...     0     0     1     0   
4207   9  19  25   5   3   0  11  20    0    0  ...     0     0     0     0   
4208  46  19   3   2   3   0   6  22    0    0  ...     1     0     0     0   

      X379  X380  X382  X383  X384  X385  
0        0     0     0     0     0     0  
1        0     0     0     0     0     0  
2        0     0     1     0     0     0  
3        0     0     0     0     0     0  
4        0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...  
4204     0     0     0     0     0     0  
4205     0     0     0     0     0     0  
4206     0     0     0     0     0     0  
4207     0     0     0     0     0     0  
4208     0     0     0     0     0     0  

[4209 rows x 364 columns]

# Perform dimensionality reduction.

In [75]:
train

X0  X1  X2  X3  X4  X5  X6  X8  X10  X12  ...  X375  X376  X377  X378  \
0     32  23  17   0   3  24   9  14    0    0  ...     0     0     1     0   
1     32  21  19   4   3  28  11  14    0    0  ...     1     0     0     0   
2     20  24  34   2   3  27   9  23    0    0  ...     0     0     0     0   
3     20  21  34   5   3  27  11   4    0    0  ...     0     0     0     0   
4     20  23  34   5   3  12   3  13    0    0  ...     0     0     0     0   
...   ..  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...   ...   ...   ...   ...   
4204   8  20  16   2   3   0   3  16    0    0  ...     1     0     0     0   
4205  31  16  40   3   3   0   7   7    0    0  ...     0     1     0     0   
4206   8  23  38   0   3   0   6   4    0    1  ...     0     0     1     0   
4207   9  19  25   5   3   0  11  20    0    0  ...     0     0     0     0   
4208  46  19   3   2   3   0   6  22    0    0  ...     1     0     0     0   

      X379  X380  X382  X383  X384  X385  
0        0     0     0     0     0     0  
1        0     0     0     0     0     0  
2        0     0     1     0     0     0  
3        0     0     0     0     0     0  
4        0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...  
4204     0     0     0     0     0     0  
4205     0     0     0     0     0     0  
4206     0     0     0     0     0     0  
4207     0     0     0     0     0     0  
4208     0     0     0     0     0     0  

[4209 rows x 364 columns]

In [76]:
x=train
x.head()

X0  X1  X2  X3  X4  X5  X6  X8  X10  X12  ...  X375  X376  X377  X378  \
0  32  23  17   0   3  24   9  14    0    0  ...     0     0     1     0   
1  32  21  19   4   3  28  11  14    0    0  ...     1     0     0     0   
2  20  24  34   2   3  27   9  23    0    0  ...     0     0     0     0   
3  20  21  34   5   3  27  11   4    0    0  ...     0     0     0     0   
4  20  23  34   5   3  12   3  13    0    0  ...     0     0     0     0   

   X379  X380  X382  X383  X384  X385  
0     0     0     0     0     0     0  
1     0     0     0     0     0     0  
2     0     0     1     0     0     0  
3     0     0     0     0     0     0  
4     0     0     0     0     0     0  

[5 rows x 364 columns]

In [77]:
y=db_train.y
y

0       130.81
1        88.53
2        76.26
3        80.62
4        78.02
         ...  
4204    107.39
4205    108.77
4206    109.22
4207     87.48
4208    110.85
Name: y, Length: 4209, dtype: float64

In [78]:
print(x.shape)
print(y.shape)

(4209, 364)
(4209,)


# Performing PCA

In [79]:
from sklearn.decomposition import PCA

In [80]:
pca=PCA(n_components=.97)

In [81]:
pca.fit(x,y)

PCA(n_components=0.97)

In [82]:
x_trans=pca.fit_transform(x)
print(np.round(x_trans,2))

[[  0.61  -0.13  15.62 ...   3.82   1.54  -0.65]
 [  0.57   1.56  17.91 ...  -0.8    0.81  -0.79]
 [ 16.2   12.29  17.63 ...   0.83   1.58  -0.61]
 ...
 [ 29.    14.86  -7.75 ...   3.4   -0.25   0.26]
 [ 22.97   1.68  -9.03 ...  -2.7    1.72   2.24]
 [-17.28  -9.95  -3.72 ...   1.25   0.8    0.81]]


In [83]:
x_trans.shape

(4209, 9)

In [84]:
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error
from math import sqrt

In [85]:
train_x,test_x,train_y,test_y = train_test_split(x_trans,y,test_size=.3,random_state=7)
print(train_x.shape)
print(train_y.shape)
print(test_x.shape)
print(test_y.shape)

(2946, 9)
(2946,)
(1263, 9)
(1263,)


In [86]:
xgb_reg = xgb.XGBRegressor()

In [87]:
model = xgb_reg.fit(train_x,train_y)

In [88]:
print('RMSE = ',sqrt(mean_squared_error(model.predict(test_x),test_y)))

RMSE =  11.188745833590177




# Predict your test_df values using XGBoost.

In [89]:
db_test.head()

X0  X1  X2  X3  X4  X5  X6  X8  X10  X11  ...  X375  X376  X377  X378  \
0  21  23  34   5   3  26   0  22    0    0  ...     0     0     0     1   
1  42   3   8   0   3   9   6  24    0    0  ...     0     0     1     0   
2  21  23  17   5   3   0   9   9    0    0  ...     0     0     0     1   
3  21  13  34   5   3  31  11  13    0    0  ...     0     0     0     1   
4  45  20  17   2   3  30   8  12    0    0  ...     1     0     0     0   

   X379  X380  X382  X383  X384  X385  
0     0     0     0     0     0     0  
1     0     0     0     0     0     0  
2     0     0     0     0     0     0  
3     0     0     0     0     0     0  
4     0     0     0     0     0     0  

[5 rows x 371 columns]

In [90]:
pca.fit(db_test)

PCA(n_components=0.97)

In [91]:
db_test_trans=pca.transform(db_test)
db_test_trans

array([[ 14.58336173,  14.16672549,  13.53857605, ...,  -2.02613083,
          2.53369118,  -1.08222714],
       [-15.25161263,  -7.73675622,  -7.45495093, ...,   4.00684487,
          1.8397268 ,   0.60035628],
       [ 11.85646482,  -1.68017313,  -9.98961457, ...,  -0.90475969,
          0.73642678,  -0.07992895],
       ...,
       [-13.44644012,   3.28858211,  -6.85236379, ...,  -2.54253101,
         -0.88554736,  -2.62905183],
       [ 24.92612306,  -4.89888665, -10.16941016, ...,   3.81211184,
         -1.87617566,  -0.25064812],
       [-15.38430983,  -7.7342545 , -15.49301063, ...,   0.42170531,
          1.22577446,   1.75652444]])

In [92]:
test_predict=model.predict(db_test_trans)
test_predict

array([ 75.41555,  89.29258,  81.64661, ..., 108.80828, 111.70862,
        97.12959], dtype=float32)

In [ ]:
#thank you